import {
    ProgramNode,
    BlockNode,
    createStmtSeqNode,
    addStmtToStmtSeqNode,
    StatementNode,
    StmtType,
    createAddRelationshipStmtNode,
    createLiteral,
    ExprType,
    createEnum,
    createGetObjectByRel,
    createBinExprNode,
    createCastExprNode,
    createUnaryExprNode,
    createCheckRelExprNode,
    createGetExprNode,
    createFindExtremeExprNode,
    createQuantifierExprNode,
    createIfExprNode,
    createWithExprNode,
    createObjectSeqNode,
    addObjectToObjectSeqNode,
} from './create_nodes.js';

export var root;
var string;
/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
export var parser = (function () {
    var o = function (k, v, o, l) { for (o = o || {}, l = k.length; l--; o[k[l]] = v); return o }, $V0 = [1, 6], $V1 = [1, 15], $V2 = [1, 7], $V3 = [1, 8], $V4 = [1, 9], $V5 = [1, 10], $V6 = [1, 11], $V7 = [1, 12], $V8 = [1, 13], $V9 = [1, 14], $Va = [1, 16], $Vb = [1, 17], $Vc = [1, 18], $Vd = [1, 19], $Ve = [1, 20], $Vf = [1, 21], $Vg = [1, 22], $Vh = [1, 25], $Vi = [1, 26], $Vj = [1, 27], $Vk = [1, 28], $Vl = [1, 29], $Vm = [1, 30], $Vn = [1, 31], $Vo = [1, 32], $Vp = [1, 33], $Vq = [1, 34], $Vr = [1, 35], $Vs = [1, 36], $Vt = [1, 8, 9, 11, 12, 16, 27, 28, 29, 30, 31, 32, 33, 34, 35, 37, 38, 39, 45, 51], $Vu = [1, 8, 9, 11, 12, 16, 29, 30, 31, 32, 33, 34, 35, 38, 39, 45, 51], $Vv = [1, 8, 9, 11, 12, 16, 29, 32, 33, 38, 39, 45, 51], $Vw = [8, 13, 14, 17, 19, 20, 21, 22, 23, 24, 25, 40, 42, 43, 47, 48, 49, 50], $Vx = [1, 100], $Vy = [16, 51], $Vz = [1, 8, 9, 11, 12, 16, 45, 51];
    var parser = {
        trace: function trace() { },
        yy: {},
        symbols_: { "error": 2, "program": 3, "stmt": 4, "block": 5, "{": 6, "stmt_seq": 7, "}": 8, ";": 9, "exp": 10, "=": 11, "+=>": 12, "ID": 13, "(": 14, "object_seq": 15, ")": 16, "CLASS_LITERAL": 17, ":": 18, "STRING": 19, "INT": 20, "DOUBLE": 21, "TRUE": 22, "FALSE": 23, "OBJ_VAR": 24, "VAR": 25, "::": 26, "->": 27, ".": 28, "IS": 29, ">": 30, "<": 31, "==": 32, "!=": 33, ">=": 34, "<=": 35, "COMPARE": 36, "AS": 37, "AND": 38, "OR": 39, "NOT": 40, "CLASS": 41, "FIND": 42, "FIND_EXTREM": 43, "[": 44, "]": 45, "AMONG": 46, "EXIST": 47, "FORALL": 48, "IF": 49, "WITH": 50, ",": 51, "$accept": 0, "$end": 1 },
        terminals_: { 2: "error", 6: "{", 8: "}", 9: ";", 11: "=", 12: "+=>", 13: "ID", 14: "(", 16: ")", 17: "CLASS_LITERAL", 18: ":", 19: "STRING", 20: "INT", 21: "DOUBLE", 22: "TRUE", 23: "FALSE", 24: "OBJ_VAR", 25: "VAR", 26: "::", 27: "->", 28: ".", 29: "IS", 30: ">", 31: "<", 32: "==", 33: "!=", 34: ">=", 35: "<=", 36: "COMPARE", 37: "AS", 38: "AND", 39: "OR", 40: "NOT", 41: "CLASS", 42: "FIND", 43: "FIND_EXTREM", 44: "[", 45: "]", 46: "AMONG", 47: "EXIST", 48: "FORALL", 49: "IF", 50: "WITH", 51: "," },
        productions_: [0, [3, 1], [3, 1], [5, 3], [7, 2], [7, 3], [4, 1], [4, 3], [4, 6], [10, 1], [10, 3], [10, 1], [10, 1], [10, 1], [10, 1], [10, 1], [10, 1], [10, 1], [10, 3], [10, 3], [10, 3], [10, 3], [10, 3], [10, 3], [10, 3], [10, 3], [10, 3], [10, 3], [10, 6], [10, 3], [10, 3], [10, 3], [10, 3], [10, 2], [10, 6], [10, 5], [10, 6], [10, 11], [10, 9], [10, 9], [10, 5], [10, 7], [15, 1], [15, 3]],
        performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
            /* this == yyval */

            var $0 = $$.length - 1;
            switch (yystate) {
                case 1:
                    root = new ProgramNode($$[$0], false); return $$[$0];
                    break;
                case 2:
                    root = new ProgramNode($$[$0], true); return $$[$0];
                    break;
                case 3:
                    this.$ = new BlockNode($$[$0 - 1]);
                    break;
                case 4:
                    this.$ = createStmtSeqNode($$[$0 - 1]);
                    break;
                case 5:
                    this.$ = addStmtToStmtSeqNode($$[$0 - 2], $$[$0 - 1]);
                    break;
                case 6:
                    this.$ = new StatementNode(StmtType.EXPR, $$[$0], null);
                    break;
                case 7:
                    this.$ = new StatementNode(StmtType.ASSIGNMENT, $$[$0 - 2], $$[$0]);
                    break;
                case 8:
                    this.$ = createAddRelationshipStmtNode($$[$0 - 5], $$[$0 - 3], $$[$0 - 1]);
                    break;
                case 9:
                    this.$ = createLiteral(ExprType.ID, $$[$0]);
                    break;
                case 10:
                    this.$ = createLiteral(ExprType.CLASS, $$[$0]);
                    break;
                case 11:
                    this.$ = createLiteral(ExprType.STRING, $$[$0]);
                    break;
                case 12:
                    this.$ = createLiteral(ExprType.INT, $$[$0]);
                    break;
                case 13:
                    this.$ = createLiteral(ExprType.DOUBLE, $$[$0]);
                    break;
                case 14:
                    this.$ = createLiteral(ExprType.BOOLEAN, true);
                    break;
                case 15:
                    this.$ = createLiteral(ExprType.BOOLEAN, false);
                    break;
                case 16:
                    this.$ = createLiteral(ExprType.OBJ_VAR, $$[$0]);
                    break;
                case 17:
                    this.$ = createLiteral(ExprType.VAR, $$[$0]);
                    break;
                case 18:
                    this.$ = createEnum($$[$0 - 2], $$[$0]);
                    break;
                case 19:
                    this.$ = createGetObjectByRel($$[$0 - 2], $$[$0]);
                    break;
                case 20:
                    this.$ = createBinExprNode(ExprType.PROPERTY, $$[$0 - 2], $$[$0]);
                    break;
                case 21:
                    this.$ = createBinExprNode(ExprType.IS, $$[$0 - 2], $$[$0]);
                    break;
                case 22:
                    this.$ = createBinExprNode(ExprType.GREATER, $$[$0 - 2], $$[$0]);
                    break;
                case 23:
                    this.$ = createBinExprNode(ExprType.LESS, $$[$0 - 2], $$[$0]);
                    break;
                case 24:
                    this.$ = createBinExprNode(ExprType.EQUAL, $$[$0 - 2], $$[$0]);
                    break;
                case 25:
                    this.$ = createBinExprNode(ExprType.NOT_EQUAL, $$[$0 - 2], $$[$0]);
                    break;
                case 26:
                    this.$ = createBinExprNode(ExprType.GE, $$[$0 - 2], $$[$0]);
                    break;
                case 27:
                    this.$ = createBinExprNode(ExprType.LE, $$[$0 - 2], $$[$0]);
                    break;
                case 28:
                    this.$ = createBinExprNode(ExprType.COMPARE, $$[$0 - 5], $$[$0 - 1]);
                    break;
                case 29:
                    this.$ = $$[$0 - 1];
                    break;
                case 30:
                    this.$ = createCastExprNode($$[$0], $$[$0 - 2]);
                    break;
                case 31:
                    this.$ = createBinExprNode(ExprType.AND, $$[$0 - 2], $$[$0]);
                    break;
                case 32:
                    this.$ = createBinExprNode(ExprType.OR, $$[$0 - 2], $$[$0]);
                    break;
                case 33:
                    this.$ = createUnaryExprNode(ExprType.NOT, $$[$0]);
                    break;
                case 34:
                    this.$ = createCheckRelExprNode($$[$0 - 5], $$[$0 - 3], $$[$0 - 1]);
                    break;
                case 35:
                    this.$ = createUnaryExprNode(ExprType.GET_CLASS, $$[$0 - 4]);
                    break;
                case 36:
                    this.$ = createGetExprNode(ExprType.FIND, $$[$0 - 4], $$[$0 - 3], $$[$0 - 1]);
                    break;
                case 37:
                    this.$ = createFindExtremeExprNode($$[$0 - 9], $$[$0 - 7], $$[$0 - 4], $$[$0 - 3], $$[$0 - 1]);
                    break;
                case 38:
                    this.$ = createQuantifierExprNode(ExprType.EXIST, $$[$0 - 7], $$[$0 - 6], $$[$0 - 4], $$[$0 - 1]);
                    break;
                case 39:
                    this.$ = createQuantifierExprNode(ExprType.FORALL, $$[$0 - 7], $$[$0 - 6], $$[$0 - 4], $$[$0 - 1]);
                    break;
                case 40:
                    this.$ = createIfExprNode($$[$0 - 2], $$[$0]);
                    break;
                case 41:
                    this.$ = createWithExprNode($$[$0 - 4], $$[$0 - 2], $$[$0]);
                    break;
                case 42:
                    this.$ = createObjectSeqNode($$[$0]);
                    break;
                case 43:
                    this.$ = addObjectToObjectSeqNode($$[$0 - 2], $$[$0]);
                    break;
            }
        },
        table: [{ 3: 1, 4: 2, 5: 3, 6: [1, 5], 10: 4, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 1: [3] }, { 1: [2, 1] }, { 1: [2, 2] }, o($V4, [2, 6], { 11: [1, 23], 12: [1, 24], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }), { 4: 38, 7: 37, 10: 4, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, o($Vt, [2, 9], { 26: [1, 39] }), { 18: [1, 40] }, o($Vt, [2, 11]), o($Vt, [2, 12]), o($Vt, [2, 13]), o($Vt, [2, 14]), o($Vt, [2, 15]), o($Vt, [2, 16]), o($Vt, [2, 17]), { 10: 41, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 42, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 13: [1, 43] }, { 13: [1, 44] }, { 13: [1, 45] }, { 13: [1, 46] }, { 14: [1, 47] }, { 14: [1, 48] }, { 10: 49, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 13: [1, 50] }, { 13: [1, 51] }, { 13: [1, 52], 36: [1, 53], 41: [1, 54] }, { 10: 55, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 56, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 57, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 58, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 59, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 60, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 61, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 62, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 63, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 64, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 4: 66, 8: [1, 65], 10: 4, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 9: [1, 67] }, { 13: [1, 68] }, { 13: [1, 69] }, { 16: [1, 70], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }, o($Vu, [2, 33], { 27: $Vh, 28: $Vi, 37: $Vq }), { 13: [1, 71] }, { 44: [1, 72] }, { 13: [1, 73] }, { 13: [1, 74] }, { 10: 75, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 13: [1, 76] }, o($V4, [2, 7], { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }), { 14: [1, 77] }, o($Vt, [2, 19], { 14: [1, 78] }), o($Vt, [2, 20]), { 14: [1, 79] }, { 14: [1, 80] }, o([1, 8, 9, 11, 12, 16, 29, 38, 39, 45, 51], [2, 21], { 27: $Vh, 28: $Vi, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq }), o($Vu, [2, 22], { 27: $Vh, 28: $Vi, 37: $Vq }), o($Vu, [2, 23], { 27: $Vh, 28: $Vi, 37: $Vq }), o($Vv, [2, 24], { 27: $Vh, 28: $Vi, 30: $Vk, 31: $Vl, 34: $Vo, 35: $Vp, 37: $Vq }), o($Vv, [2, 25], { 27: $Vh, 28: $Vi, 30: $Vk, 31: $Vl, 34: $Vo, 35: $Vp, 37: $Vq }), o($Vu, [2, 26], { 27: $Vh, 28: $Vi, 37: $Vq }), o($Vu, [2, 27], { 27: $Vh, 28: $Vi, 37: $Vq }), o($Vt, [2, 30]), o([1, 8, 9, 11, 12, 16, 38, 39, 45, 51], [2, 31], { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq }), o([1, 8, 9, 11, 12, 16, 39, 45, 51], [2, 32], { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr }), { 1: [2, 3] }, { 9: [1, 81] }, o($Vw, [2, 4]), o($Vt, [2, 18]), o($Vt, [2, 10]), o($Vt, [2, 29]), { 6: [1, 82] }, { 10: 83, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 44: [1, 84] }, { 44: [1, 85] }, { 16: [1, 86], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }, { 11: [1, 87] }, { 10: 89, 13: $V0, 14: $V1, 15: 88, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 89, 13: $V0, 14: $V1, 15: 90, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 91, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 16: [1, 92] }, o($Vw, [2, 5]), { 10: 93, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs, 45: [1, 94] }, { 10: 95, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 96, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 97, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 98, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 16: [1, 99], 51: $Vx }, o($Vy, [2, 42], { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }), { 16: [1, 101], 51: $Vx }, { 16: [1, 102], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }, o($Vt, [2, 35]), { 8: [1, 103], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }, { 46: [1, 104] }, { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs, 45: [1, 105] }, { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs, 45: [1, 106] }, o($Vz, [2, 40], { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }), { 16: [1, 107], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }, o($V4, [2, 8]), { 10: 108, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, o($Vt, [2, 34]), o($Vt, [2, 28]), o($Vt, [2, 36]), { 13: [1, 109] }, { 6: [1, 110] }, { 6: [1, 111] }, { 10: 112, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, o($Vy, [2, 43], { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }), { 13: [1, 113] }, { 10: 114, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, { 10: 115, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, o($Vz, [2, 41], { 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }), { 6: [1, 116] }, { 8: [1, 117], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }, { 8: [1, 118], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }, { 10: 119, 13: $V0, 14: $V1, 17: $V2, 19: $V3, 20: $V4, 21: $V5, 22: $V6, 23: $V7, 24: $V8, 25: $V9, 40: $Va, 42: $Vb, 43: $Vc, 47: $Vd, 48: $Ve, 49: $Vf, 50: $Vg }, o($Vt, [2, 38]), o($Vt, [2, 39]), { 8: [1, 120], 27: $Vh, 28: $Vi, 29: $Vj, 30: $Vk, 31: $Vl, 32: $Vm, 33: $Vn, 34: $Vo, 35: $Vp, 37: $Vq, 38: $Vr, 39: $Vs }, o($Vt, [2, 37])],
        defaultActions: { 2: [2, 1], 3: [2, 2], 65: [2, 3] },
        parseError: function parseError(str, hash) {
            if (hash.recoverable) {
                this.trace(str);
            } else {
                var error = new Error(str);
                error.hash = hash;
                throw error;
            }
        },
        parse: function parse(input) {
            var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
            var args = lstack.slice.call(arguments, 1);
            var lexer = Object.create(this.lexer);
            var sharedState = { yy: {} };
            for (var k in this.yy) {
                if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
                    sharedState.yy[k] = this.yy[k];
                }
            }
            lexer.setInput(input, sharedState.yy);
            sharedState.yy.lexer = lexer;
            sharedState.yy.parser = this;
            if (typeof lexer.yylloc == 'undefined') {
                lexer.yylloc = {};
            }
            var yyloc = lexer.yylloc;
            lstack.push(yyloc);
            var ranges = lexer.options && lexer.options.ranges;
            if (typeof sharedState.yy.parseError === 'function') {
                this.parseError = sharedState.yy.parseError;
            } else {
                this.parseError = Object.getPrototypeOf(this).parseError;
            }
            function popStack(n) {
                stack.length = stack.length - 2 * n;
                vstack.length = vstack.length - n;
                lstack.length = lstack.length - n;
            }
            _token_stack:
            var lex = function () {
                var token;
                token = lexer.lex() || EOF;
                if (typeof token !== 'number') {
                    token = self.symbols_[token] || token;
                }
                return token;
            };
            var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
            while (true) {
                state = stack[stack.length - 1];
                if (this.defaultActions[state]) {
                    action = this.defaultActions[state];
                } else {
                    if (symbol === null || typeof symbol == 'undefined') {
                        symbol = lex();
                    }
                    action = table[state] && table[state][symbol];
                }
                if (typeof action === 'undefined' || !action.length || !action[0]) {
                    var errStr = '';
                    expected = [];
                    for (p in table[state]) {
                        if (this.terminals_[p] && p > TERROR) {
                            expected.push('\'' + this.terminals_[p] + '\'');
                        }
                    }
                    if (lexer.showPosition) {
                        errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                    } else {
                        errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                    }
                    this.parseError(errStr, {
                        text: lexer.match,
                        token: this.terminals_[symbol] || symbol,
                        line: lexer.yylineno,
                        loc: yyloc,
                        expected: expected
                    });
                }
                if (action[0] instanceof Array && action.length > 1) {
                    throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
                }
                switch (action[0]) {
                    case 1:
                        stack.push(symbol);
                        vstack.push(lexer.yytext);
                        lstack.push(lexer.yylloc);
                        stack.push(action[1]);
                        symbol = null;
                        if (!preErrorSymbol) {
                            yyleng = lexer.yyleng;
                            yytext = lexer.yytext;
                            yylineno = lexer.yylineno;
                            yyloc = lexer.yylloc;
                            if (recovering > 0) {
                                recovering--;
                            }
                        } else {
                            symbol = preErrorSymbol;
                            preErrorSymbol = null;
                        }
                        break;
                    case 2:
                        len = this.productions_[action[1]][1];
                        yyval.$ = vstack[vstack.length - len];
                        yyval._$ = {
                            first_line: lstack[lstack.length - (len || 1)].first_line,
                            last_line: lstack[lstack.length - 1].last_line,
                            first_column: lstack[lstack.length - (len || 1)].first_column,
                            last_column: lstack[lstack.length - 1].last_column
                        };
                        if (ranges) {
                            yyval._$.range = [
                                lstack[lstack.length - (len || 1)].range[0],
                                lstack[lstack.length - 1].range[1]
                            ];
                        }
                        r = this.performAction.apply(yyval, [
                            yytext,
                            yyleng,
                            yylineno,
                            sharedState.yy,
                            action[1],
                            vstack,
                            lstack
                        ].concat(args));
                        if (typeof r !== 'undefined') {
                            return r;
                        }
                        if (len) {
                            stack = stack.slice(0, -1 * len * 2);
                            vstack = vstack.slice(0, -1 * len);
                            lstack = lstack.slice(0, -1 * len);
                        }
                        stack.push(this.productions_[action[1]][0]);
                        vstack.push(yyval.$);
                        lstack.push(yyval._$);
                        newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
                        stack.push(newState);
                        break;
                    case 3:
                        return true;
                }
            }
            return true;
        }
    };
    /* generated by jison-lex 0.3.4 */
    var lexer = (function () {
        var lexer = ({

            EOF: 1,

            parseError: function parseError(str, hash) {
                if (this.yy.parser) {
                    this.yy.parser.parseError(str, hash);
                } else {
                    throw new Error(str);
                }
            },

            // resets the lexer, sets new input
            setInput: function (input, yy) {
                this.yy = yy || this.yy || {};
                this._input = input;
                this._more = this._backtrack = this.done = false;
                this.yylineno = this.yyleng = 0;
                this.yytext = this.matched = this.match = '';
                this.conditionStack = ['INITIAL'];
                this.yylloc = {
                    first_line: 1,
                    first_column: 0,
                    last_line: 1,
                    last_column: 0
                };
                if (this.options.ranges) {
                    this.yylloc.range = [0, 0];
                }
                this.offset = 0;
                return this;
            },

            // consumes and returns one char from the input
            input: function () {
                var ch = this._input[0];
                this.yytext += ch;
                this.yyleng++;
                this.offset++;
                this.match += ch;
                this.matched += ch;
                var lines = ch.match(/(?:\r\n?|\n).*/g);
                if (lines) {
                    this.yylineno++;
                    this.yylloc.last_line++;
                } else {
                    this.yylloc.last_column++;
                }
                if (this.options.ranges) {
                    this.yylloc.range[1]++;
                }

                this._input = this._input.slice(1);
                return ch;
            },

            // unshifts one char (or a string) into the input
            unput: function (ch) {
                var len = ch.length;
                var lines = ch.split(/(?:\r\n?|\n)/g);

                this._input = ch + this._input;
                this.yytext = this.yytext.substr(0, this.yytext.length - len);
                //this.yyleng -= len;
                this.offset -= len;
                var oldLines = this.match.split(/(?:\r\n?|\n)/g);
                this.match = this.match.substr(0, this.match.length - 1);
                this.matched = this.matched.substr(0, this.matched.length - 1);

                if (lines.length - 1) {
                    this.yylineno -= lines.length - 1;
                }
                var r = this.yylloc.range;

                this.yylloc = {
                    first_line: this.yylloc.first_line,
                    last_line: this.yylineno + 1,
                    first_column: this.yylloc.first_column,
                    last_column: lines ?
                        (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                        + oldLines[oldLines.length - lines.length].length - lines[0].length :
                        this.yylloc.first_column - len
                };

                if (this.options.ranges) {
                    this.yylloc.range = [r[0], r[0] + this.yyleng - len];
                }
                this.yyleng = this.yytext.length;
                return this;
            },

            // When called from action, caches matched text and appends it on next action
            more: function () {
                this._more = true;
                return this;
            },

            // When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
            reject: function () {
                if (this.options.backtrack_lexer) {
                    this._backtrack = true;
                } else {
                    return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                        text: "",
                        token: null,
                        line: this.yylineno
                    });

                }
                return this;
            },

            // retain first n characters of the match
            less: function (n) {
                this.unput(this.match.slice(n));
            },

            // displays already matched input, i.e. for error messages
            pastInput: function () {
                var past = this.matched.substr(0, this.matched.length - this.match.length);
                return (past.length > 20 ? '...' : '') + past.substr(-20).replace(/\n/g, "");
            },

            // displays upcoming input, i.e. for error messages
            upcomingInput: function () {
                var next = this.match;
                if (next.length < 20) {
                    next += this._input.substr(0, 20 - next.length);
                }
                return (next.substr(0, 20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
            },

            // displays the character position where the lexing error occurred, i.e. for error messages
            showPosition: function () {
                var pre = this.pastInput();
                var c = new Array(pre.length + 1).join("-");
                return pre + this.upcomingInput() + "\n" + c + "^";
            },

            // test the lexed token: return FALSE when not a match, otherwise return token
            test_match: function (match, indexed_rule) {
                var token,
                    lines,
                    backup;

                if (this.options.backtrack_lexer) {
                    // save context
                    backup = {
                        yylineno: this.yylineno,
                        yylloc: {
                            first_line: this.yylloc.first_line,
                            last_line: this.last_line,
                            first_column: this.yylloc.first_column,
                            last_column: this.yylloc.last_column
                        },
                        yytext: this.yytext,
                        match: this.match,
                        matches: this.matches,
                        matched: this.matched,
                        yyleng: this.yyleng,
                        offset: this.offset,
                        _more: this._more,
                        _input: this._input,
                        yy: this.yy,
                        conditionStack: this.conditionStack.slice(0),
                        done: this.done
                    };
                    if (this.options.ranges) {
                        backup.yylloc.range = this.yylloc.range.slice(0);
                    }
                }

                lines = match[0].match(/(?:\r\n?|\n).*/g);
                if (lines) {
                    this.yylineno += lines.length;
                }
                this.yylloc = {
                    first_line: this.yylloc.last_line,
                    last_line: this.yylineno + 1,
                    first_column: this.yylloc.last_column,
                    last_column: lines ?
                        lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                        this.yylloc.last_column + match[0].length
                };
                this.yytext += match[0];
                this.match += match[0];
                this.matches = match;
                this.yyleng = this.yytext.length;
                if (this.options.ranges) {
                    this.yylloc.range = [this.offset, this.offset += this.yyleng];
                }
                this._more = false;
                this._backtrack = false;
                this._input = this._input.slice(match[0].length);
                this.matched += match[0];
                token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
                if (this.done && this._input) {
                    this.done = false;
                }
                if (token) {
                    return token;
                } else if (this._backtrack) {
                    // recover context
                    for (var k in backup) {
                        this[k] = backup[k];
                    }
                    return false; // rule action called reject() implying the next rule should be tested instead.
                }
                return false;
            },

            // return next match in input
            next: function () {
                if (this.done) {
                    return this.EOF;
                }
                if (!this._input) {
                    this.done = true;
                }

                var token,
                    match,
                    tempMatch,
                    index;
                if (!this._more) {
                    this.yytext = '';
                    this.match = '';
                }
                var rules = this._currentRules();
                for (var i = 0; i < rules.length; i++) {
                    tempMatch = this._input.match(this.rules[rules[i]]);
                    if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                        match = tempMatch;
                        index = i;
                        if (this.options.backtrack_lexer) {
                            token = this.test_match(tempMatch, rules[i]);
                            if (token !== false) {
                                return token;
                            } else if (this._backtrack) {
                                match = false;
                                continue; // rule action called reject() implying a rule MISmatch.
                            } else {
                                // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                                return false;
                            }
                        } else if (!this.options.flex) {
                            break;
                        }
                    }
                }
                if (match) {
                    token = this.test_match(match, rules[index]);
                    if (token !== false) {
                        return token;
                    }
                    // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                    return false;
                }
                if (this._input === "") {
                    return this.EOF;
                } else {
                    return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                        text: "",
                        token: null,
                        line: this.yylineno
                    });
                }
            },

            // return next match that has a token
            lex: function lex() {
                var r = this.next();
                if (r) {
                    return r;
                } else {
                    return this.lex();
                }
            },

            // activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
            begin: function begin(condition) {
                this.conditionStack.push(condition);
            },

            // pop the previously active lexer condition state off the condition stack
            popState: function popState() {
                var n = this.conditionStack.length - 1;
                if (n > 0) {
                    return this.conditionStack.pop();
                } else {
                    return this.conditionStack[0];
                }
            },

            // produce the lexer rule set which is active for the currently active lexer condition state
            _currentRules: function _currentRules() {
                if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
                    return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
                } else {
                    return this.conditions["INITIAL"].rules;
                }
            },

            // return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
            topState: function topState(n) {
                n = this.conditionStack.length - 1 - Math.abs(n || 0);
                if (n >= 0) {
                    return this.conditionStack[n];
                } else {
                    return "INITIAL";
                }
            },

            // alias for begin(condition)
            pushState: function pushState(condition) {
                this.begin(condition);
            },

            // return the number of states currently on the stack
            stateStackSize: function stateStackSize() {
                return this.conditionStack.length;
            },
            options: {},
            performAction: function anonymous(yy, yy_, $avoiding_name_collisions, YY_START) {
                var YYSTATE = YY_START;
                switch ($avoiding_name_collisions) {
                    case 0: return 22;
                        break;
                    case 1: return 23;
                        break;
                    case 2: return 41;
                        break;
                    case 3: return 42;
                        break;
                    case 4: return 43;
                        break;
                    case 5: return 29;
                        break;
                    case 6: return 38;
                        break;
                    case 7: return 39;
                        break;
                    case 8: return 40;
                        break;
                    case 9: return 36;
                        break;
                    case 10: return 47;
                        break;
                    case 11: return 48;
                        break;
                    case 12: return 'WHERE';
                        break;
                    case 13: return 46;
                        break;
                    case 14: return 49;
                        break;
                    case 15: return 50;
                        break;
                    case 16: return 37;
                        break;
                    case 17: return 17
                        break;
                    case 18: return 27;
                        break;
                    case 19: return 6;
                        break;
                    case 20: return 8;
                        break;
                    case 21: return 44;
                        break;
                    case 22: return 45;
                        break;
                    case 23: return 32;
                        break;
                    case 24: return 33;
                        break;
                    case 25: return 34;
                        break;
                    case 26: return 35;
                        break;
                    case 27: return 11;
                        break;
                    case 28: return 14;
                        break;
                    case 29: return 16;
                        break;
                    case 30: return 51;
                        break;
                    case 31: return 9;
                        break;
                    case 32: return 30;
                        break;
                    case 33: return 31;
                        break;
                    case 34: return 26;
                        break;
                    case 35: return 12;
                        break;
                    case 36: return 18;
                        break;
                    case 37: return 24;
                        break;
                    case 38: return 13;
                        break;
                    case 39: return 25;
                        break;
                    case 40: string = ''; this.begin('STRING');
                        break;
                    case 41: string += yy_.yytext;
                        break;
                    case 42: string += '\n';
                        break;
                    case 43: string += '\t';
                        break;
                    case 44: string += '\\';
                        break;
                    case 45: throw new Error('Error: invalid escape\n');
                        break;
                    case 46: throw new Error('Error: unfinished string.\n');
                        break;
                    case 47: string += '"';
                        break;
                    case 48: string += '\'';
                        break;
                    case 49: this.begin('INITIAL'); yy_.yytext = string; return 19;
                        break;
                    case 50: this.begin('INITIAL'); throw new Error('Error: expected \".\n');
                        break;
                    case 51: return 21;
                        break;
                    case 52: return 20;
                        break;
                    case 53: return 28;
                        break;
                    case 54:/* skip whitespace */
                        break;
                }
            },
            rules: [/^(?:true\b)/, /^(?:false\b)/, /^(?:getClass\b)/, /^(?:find\b)/, /^(?:findExtreme\b)/, /^(?:is\b)/, /^(?:and\b)/, /^(?:or\b)/, /^(?:not\b)/, /^(?:compare\b)/, /^(?:exist\b)/, /^(?:forall\b)/, /^(?:where\b)/, /^(?:among\b)/, /^(?:if\b)/, /^(?:with\b)/, /^(?:as\b)/, /^(?:class\b)/, /^(?:->)/, /^(?:\{)/, /^(?:\})/, /^(?:\[)/, /^(?:\])/, /^(?:==)/, /^(?:!=)/, /^(?:>=)/, /^(?:<=)/, /^(?:=)/, /^(?:\()/, /^(?:\))/, /^(?:,)/, /^(?:;)/, /^(?:>)/, /^(?:<)/, /^(?:::)/, /^(?:\+=>)/, /^(?::)/, /^(?:obj:[a-zA-Z_][A-Za-z0-9_]*)/, /^(?:[a-zA-Z_][A-Za-z0-9_]*)/, /^(?:\$[a-zA-Z_][A-Za-z0-9_]*)/, /^(?:")/, /^(?:[^\\\"\n]+)/, /^(?:\\n)/, /^(?:\\t)/, /^(?:\\\\)/, /^(?:\\[^nt\"\'\\])/, /^(?:\n)/, /^(?:\\")/, /^(?:\\')/, /^(?:")/, /^(?:$)/, /^(?:([0-9]+\.[0-9]*|[0-9]*\.[0-9]+))/, /^(?:[0-9]+)/, /^(?:\.)/, /^(?:\s+)/],
            conditions: { "STRING": { "rules": [41, 42, 43, 44, 45, 46, 47, 48, 49, 50], "inclusive": false }, "INITIAL": { "rules": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 51, 52, 53, 54], "inclusive": true } }
        });
        return lexer;
    })();
    parser.lexer = lexer;
    function Parser() {
        this.yy = {};
    }
    Parser.prototype = parser; parser.Parser = Parser;
    return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
    exports.parser = parser;
    exports.Parser = parser.Parser;
    exports.parse = function () { return parser.parse.apply(parser, arguments); };
    exports.main = function commonjsMain(args) {
        if (!args[1]) {
            console.log('Usage: ' + args[0] + ' FILE');
            process.exit(1);
        }
        var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
        return exports.parser.parse(source);
    };
    if (typeof module !== 'undefined' && require.main === module) {
        exports.main(process.argv.slice(1));
    }
}
