cat ./utils/locale.js > ./build/plugin.js
cat ./utils/style.js >> ./build/plugin.js
cat ./dictionaries/ClassPropertiesConstructor.js >> ./build/plugin.js
cat ./dictionaries/EnumConstructor.js >> ./build/plugin.js
cat ./tree_nodes/ConditionNodeConstructor.js >> ./build/plugin.js
cat ./dictionaries/RelationshipsConstructor.js >> ./build/plugin.js
cat ./dictionaries/Utils.js >> ./build/plugin.js
cat ./utils/code_to_block.js >> ./build/plugin.js
cat ./utils/create_nodes.js >> ./build/plugin.js
cat ./utils/parser.js >> ./build/plugin.js
cat ./tree_nodes/ActionNodeConstructor.js >> ./build/plugin.js
cat ./dictionaries/ClassConstructor.js >> ./build/plugin.js
cat ./dictionaries/ClassEditor.js >> ./build/plugin.js
cat ./dictionaries/EnumEditor.js >> ./build/plugin.js
cat ./dictionaries/ClassPropertiesEditor.js >> ./build/plugin.js
cat ./dictionaries/RelationshipsEditor.js >> ./build/plugin.js
cat ./utils/blockly.min.js >> ./build/plugin.js
cat ./utils/toolbox.js >> ./build/plugin.js
cat ./export/Export.js >> ./build/plugin.js
cat ./utils/blocks_definition.js >> ./build/plugin.js
cat ./utils/blocks_generator.js >> ./build/plugin.js
cat ./tree_nodes/LogicNodeConstructor.js >> ./build/plugin.js
cat ./tree_nodes/PredeterminingFactorsNodeConstructor.js >> ./build/plugin.js
cat ./tree_nodes/SwitchCaseNodeConstructor.js >> ./build/plugin.js
cat ./tree_nodes/CycleNodeConstructor.js >> ./build/plugin.js
cat ./tree_nodes/WhileNodeConstructor.js >> ./build/plugin.js
cat ./tree_nodes/StartNodeConstructor.js >> ./build/plugin.js
cat ./tree_nodes/EditTextInNode.js >> ./build/plugin.js
cat ./tree_nodes/ConditionNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/ActionNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/CycleNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/WhileNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/SwitchCaseNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/StartNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/PredeterminingFactorsNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/LogicNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/EditValueInOutcome.js >> ./build/plugin.js
cat ./tree_nodes/BranchResultNodeContructor.js >> ./build/plugin.js
cat ./tree_nodes/BranchResultNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/QuestionInfoInNodeEditor.js >> ./build/plugin.js
cat ./tree_nodes/QuestionInfoInOutcome.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToQuestionNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToActionNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToTrueNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToFalseNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToLogicNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToStartNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToPredeterminingFactorsNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToUncertaintyNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToSwitchCaseNode.js >> ./build/plugin.js
cat ./tree_nodes/ConvertToCycleNode.js >> ./build/plugin.js
cat ./utils/tree_to_xml.js >> ./build/plugin.js
cat ./utils/utils.js >> ./build/plugin.js
cat ./main.js >> ./build/plugin.js
